"""Book persistence: one JSON file per book under ``BOOKS_DIR``.

The frontend owns the tree and saves the whole book on change. These helpers
just do safe reads/writes and a little bookkeeping.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import tempfile
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

import config

DEFAULT_SETTINGS = {"tone": "Informative", "depth": "Intermediate", "palette": "popular"}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def new_id() -> str:
    return uuid.uuid4().hex


def _path(book_id: str) -> Path:
    # book_id is generated by us (hex uuid); guard anyway against traversal.
    if not re.fullmatch(r"[a-f0-9]{32}", book_id or ""):
        raise ValueError("invalid book id")
    return config.BOOKS_DIR / f"{book_id}.json"


def _trash_dir() -> Path:
    d = config.BOOKS_DIR / ".trash"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _tree_stats(book: dict) -> tuple[int, int]:
    """(node count, total content chars) for a book."""
    nodes = chars = 0

    def rec(items):
        nonlocal nodes, chars
        for n in items:
            nodes += 1
            chars += len(n.get("content") or "")
            rec(n.get("children") or [])

    rec(book.get("nodes") or [])
    return nodes, chars


_SNAPSHOT_EVERY = 90        # seconds between routine snapshots per book
_KEEP_SNAPSHOTS = 8


def _maybe_snapshot(book_id: str, old_text: str, new_book: dict) -> None:
    """Copy the previous file into .trash before it's overwritten, if enough
    time has passed or the new version looks like it lost a lot of work."""
    try:
        old_book = json.loads(old_text)
    except json.JSONDecodeError:
        old_book = {}
    trash = _trash_dir()
    existing = sorted(trash.glob(f"{book_id}__*.json"))

    fresh_enough = (
        not existing
        or (time.time() - existing[-1].stat().st_mtime) > _SNAPSHOT_EVERY
    )

    o_nodes, o_chars = _tree_stats(old_book)
    n_nodes, n_chars = _tree_stats(new_book)
    shrank = n_nodes < o_nodes or (o_chars > 500 and n_chars < o_chars * 0.75)

    if not (fresh_enough or shrank):
        return

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    dest = trash / f"{book_id}__{stamp}Z.json"
    n = 1
    while dest.exists():
        dest = trash / f"{book_id}__{stamp}-{n}Z.json"
        n += 1
    dest.write_text(old_text, encoding="utf-8")
    for stale in sorted(trash.glob(f"{book_id}__*.json"))[:-_KEEP_SNAPSHOTS]:
        stale.unlink(missing_ok=True)


def list_versions(book_id: str) -> list[dict]:
    _path(book_id)
    out = []
    for p in sorted(_trash_dir().glob(f"{book_id}__*.json"), reverse=True):
        stamp = p.stem.split("__", 1)[1]
        out.append({"file": p.name, "savedAt": stamp, "size": p.stat().st_size})
    return out


def restore_version(book_id: str, filename: str) -> dict:
    p = _trash_dir() / filename
    if not p.exists() or not filename.startswith(f"{book_id}__"):
        raise KeyError(filename)
    data = json.loads(p.read_text(encoding="utf-8"))
    return save_book(book_id, data)


def assets_dir(book_id: str) -> Path:
    """Directory holding a book's uploaded images (created on demand)."""
    _path(book_id)  # validates the id
    d = config.BOOKS_DIR / "assets" / book_id
    d.mkdir(parents=True, exist_ok=True)
    return d


def list_books() -> list[dict]:
    out = []
    for p in sorted(config.BOOKS_DIR.glob("*.json")):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        out.append({
            "id": data.get("id", p.stem),
            "title": data.get("title", "Untitled"),
            "topic": data.get("topic", ""),
            "updatedAt": data.get("updatedAt", ""),
        })
    out.sort(key=lambda b: b.get("updatedAt", ""), reverse=True)
    return out


def get_book(book_id: str) -> dict | None:
    p = _path(book_id)
    if not p.exists():
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def create_book(topic: str, title: str = "") -> dict:
    book_id = new_id()
    book = {
        "id": book_id,
        "title": (title or topic or "Untitled").strip(),
        "topic": (topic or title or "").strip(),
        "createdAt": _now(),
        "updatedAt": _now(),
        "settings": dict(DEFAULT_SETTINGS),
        "nodes": [],
    }
    _write(book_id, book)
    return book


def save_book(book_id: str, book: dict) -> dict:
    existing = get_book(book_id)
    if existing is None:
        raise KeyError(book_id)
    book = dict(book)
    book["id"] = book_id
    book.setdefault("createdAt", existing.get("createdAt", _now()))
    book["updatedAt"] = _now()
    book.setdefault("nodes", [])
    book["settings"] = {**DEFAULT_SETTINGS, **(existing.get("settings") or {}),
                        **(book.get("settings") or {})}
    _write(book_id, book)
    return book


def delete_book(book_id: str) -> bool:
    p = _path(book_id)
    existed = p.exists()
    if existed:
        p.unlink()
    shutil.rmtree(config.BOOKS_DIR / "assets" / book_id, ignore_errors=True)
    return existed


def import_book(data: dict) -> dict:
    """Save an uploaded book JSON as a brand-new book (fresh id)."""
    if not isinstance(data, dict) or not isinstance(data.get("nodes"), list):
        raise ValueError("not a Rextbooks book (missing 'nodes' list)")
    book_id = new_id()
    book = {
        "id": book_id,
        "title": (data.get("title") or data.get("topic") or "Imported book").strip(),
        "topic": (data.get("topic") or "").strip(),
        "createdAt": _now(),
        "updatedAt": _now(),
        "settings": {**DEFAULT_SETTINGS, **(data.get("settings") or {})},
        "nodes": data.get("nodes") or [],
    }
    _write(book_id, book)
    return book


def _write(book_id: str, book: dict) -> None:
    p = _path(book_id)
    if p.exists():
        try:
            _maybe_snapshot(book_id, p.read_text(encoding="utf-8"), book)
        except OSError:
            pass
    fd, tmp = tempfile.mkstemp(dir=p.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(book, f, ensure_ascii=False, indent=2)
        os.replace(tmp, p)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


# --- tree lookup used by the AI endpoint to resolve context ------------------

def find_node(nodes: list[dict], node_id: str, parent: dict | None = None):
    """Return (node, parent) for ``node_id`` or (None, None)."""
    for n in nodes:
        if n.get("id") == node_id:
            return n, parent
        found, fparent = find_node(n.get("children", []), node_id, n)
        if found is not None:
            return found, fparent
    return None, None


def node_as_text(node: dict, *, limit: int = 200_000) -> str:
    """Flatten a node and its whole subtree to plain text (titles + section
    bodies), for feeding to the LLM as reference context. Truncated to ``limit``."""
    parts: list[str] = []

    def rec(n: dict, depth: int) -> None:
        title = (n.get("title") or "").strip()
        ntype = n.get("type")
        if ntype == "section":
            body = (n.get("content") or "").strip()
            if body:
                parts.append(body)
        elif title:
            parts.append("#" * min(depth + 1, 4) + " " + title)
        for child in n.get("children") or []:
            rec(child, depth + 1)

    rec(node, 0)
    text = "\n\n".join(parts).strip()
    if len(text) > limit:
        text = text[:limit].rsplit("\n", 1)[0] + "\n\n… (truncated)"
    return text
